// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '', // generar el firebase_options o poner apikey correspondiente.
    appId: '1:339054675940:web:0f5524ad4b74733f4729f1',
    messagingSenderId: '339054675940',
    projectId: 'ut7dinfirebase',
    authDomain: 'ut7dinfirebase.firebaseapp.com',
    storageBucket: 'ut7dinfirebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:339054675940:android:896e95081a47aa2e4729f1',
    messagingSenderId: '339054675940',
    projectId: 'ut7dinfirebase',
    storageBucket: 'ut7dinfirebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:339054675940:ios:11c2650893ce90734729f1',
    messagingSenderId: '339054675940',
    projectId: 'ut7dinfirebase',
    storageBucket: 'ut7dinfirebase.firebasestorage.app',
    iosBundleId: 'com.example.ut6Multipantalla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:339054675940:ios:11c2650893ce90734729f1',
    messagingSenderId: '339054675940',
    projectId: 'ut7dinfirebase',
    storageBucket: 'ut7dinfirebase.firebasestorage.app',
    iosBundleId: 'com.example.ut6Multipantalla',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:339054675940:web:f09e25ededdd8d6e4729f1',
    messagingSenderId: '339054675940',
    projectId: 'ut7dinfirebase',
    authDomain: 'ut7dinfirebase.firebaseapp.com',
    storageBucket: 'ut7dinfirebase.firebasestorage.app',
  );
}
